version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: top-mailhog
      ports:
        - "8025:8025"

    redis:
      image: redis:alpine
      container_name: top-redis

    postgres:
      image: postgres:10.3-alpine
      container_name: top-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=api
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=top
      ports:
        - "5432:5432"

    webserver:
      image: nginx:alpine
      container_name: top-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-cli:
      build: docker/php-fpm
      container_name: top-php-cli
      working_dir: /application
      env_file:
        - .env
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    php-fpm:
      build: docker/php-fpm
      container_name: top-php-fpm
      working_dir: /application
      env_file:
        - .env
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    php-queue-worker:
      build: docker/php-fpm
      container_name: top-php-queue-worker
      working_dir: /application
      env_file:
        - .env
      command: php artisan queue:work
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
