version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: api-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: api-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: api-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=api

    webserver:
      image: nginx:alpine
      container_name: api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: api-php-fpm
      working_dir: /application
      env_file:
        - .env
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

